name: CI
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: test
        run: |
          set -x
          docker build -t academiaonline/phpinfo:test .
          docker run -d --name phpinfo -p 80:8080 academiaonline/phpinfo:test
          while true
            do  sleep 10
            docker logs phpinfo 2>& 1 | grep 'PHP .* Development Server .* started' && break
            done
          while true
            do  sleep 10
                curl -s localhost | grep "PHP.*phpinfo()" && break
            done
